schema_version: 1

context:
  name: at-cascade
  version: 2025.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bradbell/at_cascade/archive/${{ version }}.tar.gz
  sha256: 39954cde2cd603142d0535fe3a9dc68adbac2b15765d82bd74a8384e64fc51a3
  # patches:
  #   - ${{ version }}.patch

# build.sh and build.bat run all the at_cascade tests
# using the code in its source directory (sandbox).
#
# They then install at_cascade using pip as in commented out scipt entry below.
build:
  number: 0
  noarch: python
  # script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
    - dismod-at
    - numpy
    - scipy
  run:
    - python >=3.8
    - dismod-at
    - numpy
    - scipy

tests:
  - python:
      imports:
        - at_cascade
      pip_check: true
  #
  # Run one of the sandbox tests using the installed version of at_cascade.
  - script:
      # python example/csv/sim_fit_pred.py
      interpreter: python
      content:  exec( open('example/csv/sim_fit_pred.py').read() )
    requirements:
      run:
        - python
        - dismod-at
        - numpy
        - matplotlib
        - scipy
    files:
      source:
        - example/csv/sim_fit_pred.py

about:
  summary: Cascading dismod_at from parent to child regions
  license: AGPL-3.0-or-later
  license_file: agpl-3.0.txt
  homepage: https://at-cascade.readthedocs.io/stable-2025/
  repository: https://github.com/bradbell/at_cascade
  documentation:  https://at-cascade.readthedocs.io/stable-2025/

extra:
  recipe-maintainers:
    - bradbell

